In [1]:
import numpy as np
np.random.seed(10)
sales = np.random.randint(1000, 10000, size=(50, 4))
print("Sales Data:\n", sales)

Sales Data:
 [[2289 8293 2344 8291]
 [5829 2520 7400 6648]
 [5452 1239 3443 3102]
 [4416 8290 1574 9036]
 [7899 1409 2406 1653]
 [4932 2366 9281 3700]
 [8489 2828 1283 9285]
 [8063 3654 5491 8561]
 [7159 4602 1630 6191]
 [4416 2681 2159 7859]
 [9988 7945 3810 1044]
 [3693 3052 8512 6976]
 [8350 1360 3703 4069]
 [2270 3645 7768 5876]
 [5576 9254 2526 9177]
 [3412 1232 4626 3797]
 [7457 5843 3866 3605]
 [8845 1914 2539 3845]
 [8952 2362 2103 8411]
 [4125 1921 6486 9112]
 [7929 8505 8913 9478]
 [8377 9593 4216 5767]
 [6477 5297 7566 3814]
 [1534 4680 8235 8263]
 [5451 2106 3110 4830]
 [2613 1506 7109 6869]
 [1459 3033 4493 6013]
 [5776 4429 5442 6703]
 [7792 8893 3376 1412]
 [2279 5973 8710 1985]
 [7350 6333 5030 6133]
 [4753 3564 7871 7684]
 [9743 5443 5199 5873]
 [6383 5246 3080 4843]
 [2204 8116 6828 7302]
 [2006 5472 9052 7474]
 [8966 3185 3306 8142]
 [9845 5532 5741 3269]
 [7127 5436 8088 2834]
 [2527 5446 4158 8621]
 [7957 2458 4568 6676]
 [1875 3765 8067 5551]
 [3520 2127 9247 2926

In [2]:
store_ids = np.arange(1, 51)
data = np.column_stack((store_ids, sales))
print("Combined Data:\n", data)

Combined Data:
 [[   1 2289 8293 2344 8291]
 [   2 5829 2520 7400 6648]
 [   3 5452 1239 3443 3102]
 [   4 4416 8290 1574 9036]
 [   5 7899 1409 2406 1653]
 [   6 4932 2366 9281 3700]
 [   7 8489 2828 1283 9285]
 [   8 8063 3654 5491 8561]
 [   9 7159 4602 1630 6191]
 [  10 4416 2681 2159 7859]
 [  11 9988 7945 3810 1044]
 [  12 3693 3052 8512 6976]
 [  13 8350 1360 3703 4069]
 [  14 2270 3645 7768 5876]
 [  15 5576 9254 2526 9177]
 [  16 3412 1232 4626 3797]
 [  17 7457 5843 3866 3605]
 [  18 8845 1914 2539 3845]
 [  19 8952 2362 2103 8411]
 [  20 4125 1921 6486 9112]
 [  21 7929 8505 8913 9478]
 [  22 8377 9593 4216 5767]
 [  23 6477 5297 7566 3814]
 [  24 1534 4680 8235 8263]
 [  25 5451 2106 3110 4830]
 [  26 2613 1506 7109 6869]
 [  27 1459 3033 4493 6013]
 [  28 5776 4429 5442 6703]
 [  29 7792 8893 3376 1412]
 [  30 2279 5973 8710 1985]
 [  31 7350 6333 5030 6133]
 [  32 4753 3564 7871 7684]
 [  33 9743 5443 5199 5873]
 [  34 6383 5246 3080 4843]
 [  35 2204 8116 6828 7302]
 [  

In [3]:
prodA, prodB, prodC, prodD = np.split(sales, 4, axis=1)
prodA = prodA.flatten()
prodB = prodB.flatten()
prodC = prodC.flatten()
prodD = prodD.flatten()

In [4]:
print("Mean Sales:", np.mean(sales, axis=0))

Mean Sales: [5728.6  4687.52 5242.42 5936.56]


In [5]:
print("Median Sales:", np.median(sales, axis=0))

Median Sales: [5802.5 4515.5 4627.  6162. ]


In [6]:
print("Variance:", np.var(sales, axis=0))

Variance: [6218565.32   6163411.0496 6145181.0836 5791355.0864]


In [7]:
print("Standard Deviation:", np.std(sales, axis=0))

Standard Deviation: [2493.70513894 2482.62180962 2478.94757581 2406.52344397]


In [8]:
print("95th Percentile:", np.percentile(sales, 95, axis=0))

95th Percentile: [9393.35 9091.55 9159.25 9169.8 ]


In [9]:
def mode(arr):
    values, counts = np.unique(arr, return_counts=True)
    return values[np.argmax(counts)]

print("Mode Product A:", mode(prodA))

Mode Product A: 4416


In [10]:
print("First 5 Stores:\n", data[:5])

First 5 Stores:
 [[   1 2289 8293 2344 8291]
 [   2 5829 2520 7400 6648]
 [   3 5452 1239 3443 3102]
 [   4 4416 8290 1574 9036]
 [   5 7899 1409 2406 1653]]


In [12]:
print("First 10 Stores:\n", data[1:11])

First 10 Stores:
 [[   2 5829 2520 7400 6648]
 [   3 5452 1239 3443 3102]
 [   4 4416 8290 1574 9036]
 [   5 7899 1409 2406 1653]
 [   6 4932 2366 9281 3700]
 [   7 8489 2828 1283 9285]
 [   8 8063 3654 5491 8561]
 [   9 7159 4602 1630 6191]
 [  10 4416 2681 2159 7859]
 [  11 9988 7945 3810 1044]]


In [13]:
weights = np.array([0.3, 0.25, 0.25, 0.2])
weighted_sales = np.dot(sales, weights)
print("Weighted Sales:\n", weighted_sales)

Weighted Sales:
 [5004.15 5558.3  3426.5  5598.   3654.05 5131.35 5431.45 6417.35 4943.9
 4106.6  6143.95 5394.1  4584.55 4709.45 6453.2  3247.5  5385.35 4535.75
 5484.05 5161.65 8628.8  7118.75 5921.65 5341.55 3905.3  4311.45 3521.8
 5541.15 5687.25 4751.45 6272.35 5821.45 6758.   4965.   5857.6  5727.6
 5940.95 6425.55 6085.9  4883.3  5478.8  4630.7  4484.7  7002.45 6475.85
 6349.55 6459.45 5836.6  4136.3  4726.4 ]


In [14]:
normalized_sales = (weighted_sales - np.min(weighted_sales)) / (np.max(weighted_sales) - np.min(weighted_sales))

print("Normalized Sales:\n", normalized_sales)

Normalized Sales:
 [0.32643599 0.42941297 0.03326334 0.43679037 0.07554866 0.3500734
 0.4058406  0.58904911 0.31523981 0.15964544 0.53824355 0.39889989
 0.24846227 0.27167227 0.59571107 0.         0.39727389 0.23939383
 0.41561519 0.35570401 1.         0.71938937 0.49693383 0.3891346
 0.12223812 0.19771245 0.05097281 0.426226   0.45337558 0.27947708
 0.56210395 0.47831379 0.65235166 0.3191608  0.4850315  0.46087377
 0.50052032 0.59057291 0.52745619 0.30397859 0.41463959 0.25703826
 0.22990727 0.69777749 0.59992009 0.57644993 0.5968725  0.4811291
 0.16516455 0.27482207]


In [15]:
rank_indices = np.argsort(-weighted_sales)

print("Top 5 Stores:")
print(store_ids[rank_indices[:5]])

Top 5 Stores:
[21 22 44 33 45]


In [18]:
X = np.random.randint(100, 1000, size=(100, 3))
true_weights = np.array([50, 20, 5])  
noise = np.random.randn(100) * 1000
y = X @ true_weights + noise 
X_T = X.T
product = X_T @ X  

In [19]:
det_value = np.linalg.det(product)
print("Determinant:", det_value)

Determinant: 2.9389059381722947e+21


In [20]:
inverse_matrix = np.linalg.inv(product)

In [21]:
beta = np.linalg.inv(X_T @ X) @ X_T @ y
print("Predicted Weights:", beta)

Predicted Weights: [50.15614626 20.15057464  4.84506659]


In [22]:
y_pred = X @ beta
mse = np.mean((y - y_pred) ** 2)
print("MSE:", mse)

MSE: 1035411.7769713152


In [23]:
normalized_sales = (y_pred - np.min(y_pred)) / (np.max(y_pred) - np.min(y_pred))

In [24]:
rank_index = np.argsort(-y_pred)
print("Top 5 Stores:", rank_index[:5])

Top 5 Stores: [46 33 47 54 24]
