In [1]:
import numpy as np
marks = np.array([[85, 90, 88],
                  [78, 76, 80],
                  [92, 89, 95],
                  [70, 75, 72],
                  [88, 84, 91]])
total_marks = np.sum(marks, axis=1)
average_subject = np.mean(marks, axis=0)
top_student = np.argmax(total_marks)
print("Total Marks per Student:", total_marks)
print("Average per Subject:", average_subject)
print("Top Scoring Student Index:", top_student)

Total Marks per Student: [263 234 276 217 263]
Average per Subject: [82.6 82.8 85.2]
Top Scoring Student Index: 2


In [2]:
import numpy as np

salaries = np.array([25000, 30000, 28000, 35000])
bonus_percent = np.array([10, 15, 12, 8])

# Broadcasting
bonus_amount = salaries * bonus_percent / 100
new_salary = salaries + bonus_amount

print("Bonus Amount:", bonus_amount)
print("New Salaries:", new_salary)

Bonus Amount: [2500. 4500. 3360. 2800.]
New Salaries: [27500. 34500. 31360. 37800.]


In [3]:
import numpy as np

A = np.array([[2, 1],
              [1, 3]])

B = np.array([5, 6])

# Solve AX = B
solution = np.linalg.solve(A, B)

print("Solution (x, y):", solution)

Solution (x, y): [1.8 1.4]


In [4]:
import numpy as np

A = np.array([[2, 1, 3],
              [1, 0, 2],
              [4, 1, 8]])

det = np.linalg.det(A)
print("Determinant:", det)
if det != 0:
    print("Inverse exists")
    inverse = np.linalg.inv(A)
    print("Inverse Matrix:\n", inverse)
    eigenvalues, eigenvectors = np.linalg.eig(A)
    print("Eigenvalues:", eigenvalues)
    result = np.dot(A, inverse)
    print("A:\n", result)
    
else:
    print("Inverse does not exist")

Determinant: -1.0
Inverse exists
Inverse Matrix:
 [[ 2.  5. -2.]
 [ 0. -4.  1.]
 [-1. -2.  1.]]
Eigenvalues: [ 9.88864745  0.37851665 -0.26716411]
A:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
