In [1]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

print("Original Array:\n", arr)

print("First Row:", arr[0])
print("Last Column:", arr[:, -1])
print("Middle 2x2 Matrix:\n", arr[1:3, 1:3])

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row: [1 2 3 4]
Last Column: [ 4  8 12 16]
Middle 2x2 Matrix:
 [[ 6  7]
 [10 11]]


In [2]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

result = a + b
result = a - b

print("Array A:\n", a)
print("Array B:", b)
print("Broadcasting Result:\n", result)

Array A:
 [[1 2 3]
 [4 5 6]]
Array B: [10 20 30]
Broadcasting Result:
 [[ -9 -18 -27]
 [ -6 -15 -24]]


In [3]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Sum:", np.sum(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Sum: 150
Max: 50
Min: 10


In [4]:
import numpy as np

arr = np.array([5, 12, 7, 18, 3, 25])

print("Original Array:", arr)

filtered = arr[arr > 10]

print("Elements greater than 10:", filtered)

Original Array: [ 5 12  7 18  3 25]
Elements greater than 10: [12 18 25]


In [5]:
import numpy as np

matrix = np.array([[4, 2],
                   [3, 1]])

print("Matrix:\n", matrix)

det = np.linalg.det(matrix)
print("Determinant:", det)

if det != 0:
    inv = np.linalg.inv(matrix)
    print("Inverse:\n", inv)
    
    identity = np.dot(matrix, inv)
    print("Matrix Inverse:\n", identity)
else:
    print("Inverse does not exist")

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Matrix:
 [[4 2]
 [3 1]]
Determinant: -2.0
Inverse:
 [[-0.5  1. ]
 [ 1.5 -2. ]]
Matrix Inverse:
 [[1. 0.]
 [0. 1.]]
Eigenvalues: [ 5.37228132 -0.37228132]
Eigenvectors:
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]
