In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr1)
print("Shape:", arr1.shape)
print("Dimension:", arr1.ndim)
print("Size:", arr1.size)

1D Array: [10 20 30 40 50]
Shape: (5,)
Dimension: 1
Size: 5


In [4]:
import numpy as np

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Number of dimensions:", arr2.ndim)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2


In [5]:
import numpy as np

arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:\n", arr3)
print("Shape:", arr3.shape)
print("Dimension:", arr3.ndim)
print("Size:", arr3.size)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimension: 3
Size: 8


In [6]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
